name: pokemu_basic_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  convex_bottom_bar: ^3.2.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  flutter_tabler_icons: ^1.43.0
  go_router: ^15.1.2
  intl: ^0.20.2
  lottie: ^3.1.3
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/pokemu_app_icon_512.png"
  adaptive_icon_background: "assets/icons/back512.png"
  adaptive_icon_foreground: "assets/icons/fore512.png"
  min_sdk_android: 25

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - .env
  fonts:
    - family: Subjectivity
      fonts:
        - asset: assets/fonts/Subjectivity-Medium.otf
          weight: 500
        - asset: assets/fonts/Subjectivity-Bold.otf
          weight: 700
        - asset: assets/fonts/Subjectivity-Black.otf
          weight: 900
    - family: Parkinsans
      fonts:
        - asset: assets/fonts/Parkinsans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Parkinsans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Parkinsans-ExtraBold.ttf
          weight: 800
    - family: MomoSignature
      fonts:
        - asset: assets/fonts/MomoSignature-Regular.ttf
          weight: 500
  